# require 'pieces/pawn'
# require 'pieces/knight'
# require 'pieces/king'
# require 'pieces/rook'
# require 'pieces/biship'
# require 'pieces/queen'

require_relative 'pieces/bishop'
require_relative 'pieces/king'
require_relative 'pieces/knight'
require_relative 'pieces/pawn'
require_relative 'pieces/queen'
require_relative 'pieces/rook'